
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hllrrffxfqyqqigyxujm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbHJyZmZ4ZnF5cXFpZ3l4dWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTcyMTcsImV4cCI6MjA2MjA5MzIxN30.t-mBv3a3i2CKW3r4jRgm7E6hh2g2OihJqnUbvnAM7CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using 'any' to bypass type errors for now since we cannot modify the types.ts file
// This is not ideal but necessary until the supabase types are updated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
